In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('imdb_top_movies_1980_2026.csv')

In [ ]:
df.query

NameError: name 'df' is not defined

In [7]:
df.head()

,imdb_id,title,original_title,year,runtime_minutes,genres,average_rating,num_votes,imdb_url
0,tt0111161,The Shawshank Redemption,The Shawshank Redemption,1994,142.0,Drama,9.3,3182733,https://www.imdb.com/title/tt0111161
1,tt0468569,The Dark Knight,The Dark Knight,2008,152.0,"Action,Crime,Drama",9.1,3161984,https://www.imdb.com/title/tt0468569
2,tt1375666,Inception,Inception,2010,148.0,"Action,Adventure,Sci-Fi",8.8,2811692,https://www.imdb.com/title/tt1375666
3,tt0137523,Fight Club,Fight Club,1999,139.0,"Crime,Drama,Thriller",8.8,2601984,https://www.imdb.com/title/tt0137523
4,tt0816692,Interstellar,Interstellar,2014,169.0,"Adventure,Drama,Sci-Fi",8.7,2521607,https://www.imdb.com/title/tt0816692

In [10]:
df.columns

Index(['imdb_id', 'title', 'original_title', 'year', 'runtime_minutes',
       'genres', 'average_rating', 'num_votes', 'imdb_url'],
      dtype='object')

In [12]:
df.tail(3)

,imdb_id,title,original_title,year,runtime_minutes,genres,average_rating,num_votes,imdb_url
16249,tt10994688,The Binge,The Binge,2020,98.0,Comedy,5.3,5000,https://www.imdb.com/title/tt10994688
16250,tt0263743,Billionaire,Milyarder,1987,96.0,"Comedy,Drama",7.5,5000,https://www.imdb.com/title/tt0263743
16251,tt1921078,Saint Petersburg,San Peterzburg,2010,120.0,"Comedy,Crime,Drama",6.4,5000,https://www.imdb.com/title/tt1921078

In [16]:
df.shape

(16252, 9)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16252 entries, 0 to 16251
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   imdb_id          16252 non-null  object
 1   title            16252 non-null  object
 2   original_title   16252 non-null  object
 3   year             16252 non-null  int64
 4   runtime_minutes  16251 non-null  float64
 5   genres           16246 non-null  object
 6   average_rating   16252 non-null  float64
 7   num_votes        16252 non-null  int64
 8   imdb_url         16252 non-null  object
dtypes: float64(2), int64(2), object(5)
memory usage: 1.1+ MB

In [21]:
df['year']

0        1994
1        2008
2        2010
3        1999
4        2014
         ...
16247    2016
16248    1991
16249    2020
16250    1987
16251    2010
Name: year, Length: 16252, dtype: int64

In [ ]:
df['year'].head()

0    1994
1    2008
2    2010
3    1999
4    2014
Name: year, dtype: int64

In [25]:
df[['title', 'year', 'runtime_minutes', 'average_rating', 'num_votes']].head()

                      title  year  runtime_minutes  average_rating  num_votes
0  The Shawshank Redemption  1994            142.0             9.3    3182733
1           The Dark Knight  2008            152.0             9.1    3161984
2                 Inception  2010            148.0             8.8    2811692
3                Fight Club  1999            139.0             8.8    2601984
4              Interstellar  2014            169.0             8.7    2521607

In [ ]:
# .loc sempre faz slicing INCLUSIVO, ou seja, inclui o elemento do índice final inserido

df.loc[1:4, ['title', 'year']]

             title  year
1  The Dark Knight  2008
2        Inception  2010
3       Fight Club  1999
4     Interstellar  2014

In [28]:
df.iloc[1:4, 1:4]

             title   original_title  year
1  The Dark Knight  The Dark Knight  2008
2        Inception        Inception  2010
3       Fight Club       Fight Club  1999

In [35]:
df['year'] > 2003

0        False
1         True
2         True
3        False
4         True
         ...
16247     True
16248    False
16249     True
16250    False
16251     True
Name: year, Length: 16252, dtype: bool

In [34]:
df.loc[df['year'] > 2003]

,imdb_id,title,original_title,year,runtime_minutes,genres,average_rating,num_votes,imdb_url
1,tt0468569,The Dark Knight,The Dark Knight,2008,152.0,"Action,Crime,Drama",9.1,3161984,https://www.imdb.com/title/tt0468569
2,tt1375666,Inception,Inception,2010,148.0,"Action,Adventure,Sci-Fi",8.8,2811692,https://www.imdb.com/title/tt1375666
4,tt0816692,Interstellar,Interstellar,2014,169.0,"Adventure,Drama,Sci-Fi",8.7,2521607,https://www.imdb.com/title/tt0816692
11,tt1345836,The Dark Knight Rises,The Dark Knight Rises,2012,164.0,"Action,Crime,Drama",8.4,1990793,https://www.imdb.com/title/tt1345836
13,tt1853728,Django Unchained,Django Unchained,2012,165.0,"Drama,Western",8.5,1879878,https://www.imdb.com/title/tt1853728
...,...,...,...,...,...,...,...,...,...
16244,tt19864832,La Cocina,La cocina,2024,139.0,"Drama,Romance",7.0,5003,https://www.imdb.com/title/tt19864832
16245,tt4992086,Bhale Bhale Magadivoy,Bhale Bhale Magadivoy,2015,137.0,"Comedy,Romance",7.7,5002,https://www.imdb.com/title/tt4992086
16247,tt3544218,Belgica,Belgica,2016,127.0,Drama,6.7,5001,https://www.imdb.com/title/tt3544218
16249,tt10994688,The Binge,The Binge,2020,98.0,Comedy,5.3,5000,https://www.imdb.com/title/tt10994688
16251,tt1921078,Saint Petersburg,San Peterzburg,2010,120.0,"Comedy,Crime,Drama",6.4,5000,https://www.imdb.com/title/tt1921078

In [36]:
df.loc[df['year'] > 2003].shape

(11485, 9)

In [39]:
df.loc[(df['year'] > 2020) & (df['average_rating'] > 8.0)]

,imdb_id,title,original_title,year,runtime_minutes,genres,average_rating,num_votes,imdb_url
75,tt15398776,Oppenheimer,Oppenheimer,2023,180.0,"Biography,Drama,History",8.2,1024108,https://www.imdb.com/title/tt15398776
76,tt10872600,Spider-Man: No Way Home,Spider-Man: No Way Home,2021,148.0,"Action,Adventure,Fantasy",8.1,1017592,https://www.imdb.com/title/tt10872600
127,tt1745960,Top Gun: Maverick,Top Gun: Maverick,2022,130.0,"Action,Drama",8.2,857058,https://www.imdb.com/title/tt1745960
180,tt15239678,Dune: Part Two,Dune: Part Two,2024,166.0,"Action,Adventure,Drama",8.4,737414,https://www.imdb.com/title/tt15239678
273,tt10811166,The Kashmir Files,The Kashmir Files,2022,170.0,Drama,8.5,578850,https://www.imdb.com/title/tt10811166
...,...,...,...,...,...,...,...,...,...
15325,tt15964372,Aparajito,Aparajito,2022,138.0,"Biography,Drama,Family",8.7,5574,https://www.imdb.com/title/tt15964372
15463,tt16492636,Demon Slayer: Kimetsu no Yaiba - Asakusa Arc,Kimetsu no Yaiba: Asakusa-hen,2021,103.0,"Action,Animation,Fantasy",8.5,5469,https://www.imdb.com/title/tt16492636
15466,tt27302079,Aattam,Aattam,2023,139.0,"Drama,Mystery,Thriller",8.1,5466,https://www.imdb.com/title/tt27302079
15933,tt33022710,Ocean with David Attenborough,Ocean with David Attenborough,2025,95.0,Documentary,8.5,5182,https://www.imdb.com/title/tt33022710
15954,tt32292009,Laggam,Laggam,2024,130.0,Family,8.2,5161,https://www.imdb.com/title/tt32292009

In [ ]:
# Especificando as colunas que quero retornar 

df.loc[(df['year'] > 2020) & (df['average_rating'] > 8.0), ['title', 'year', 'average_rating']]

                                              title  year  average_rating
75                                      Oppenheimer  2023             8.2
76                          Spider-Man: No Way Home  2021             8.1
127                               Top Gun: Maverick  2022             8.2
180                                  Dune: Part Two  2024             8.4
273                               The Kashmir Files  2022             8.5
...                                             ...   ...             ...
15325                                     Aparajito  2022             8.7
15463  Demon Slayer: Kimetsu no Yaiba - Asakusa Arc  2021             8.5
15466                                        Aattam  2023             8.1
15933                 Ocean with David Attenborough  2025             8.5
15954                                        Laggam  2024             8.2

[88 rows x 3 columns]

In [ ]:
df.loc[(df['year'] < 2000) | (df['average_rating'] < 8.0)]

,imdb_id,title,original_title,year,runtime_minutes,genres,average_rating,num_votes,imdb_url
0,tt0111161,The Shawshank Redemption,The Shawshank Redemption,1994,142.0,Drama,9.3,3182733,https://www.imdb.com/title/tt0111161
3,tt0137523,Fight Club,Fight Club,1999,139.0,"Crime,Drama,Thriller",8.8,2601984,https://www.imdb.com/title/tt0137523
5,tt0109830,Forrest Gump,Forrest Gump,1994,142.0,"Drama,Romance",8.8,2492584,https://www.imdb.com/title/tt0109830
6,tt0110912,Pulp Fiction,Pulp Fiction,1994,154.0,"Crime,Drama",8.8,2431723,https://www.imdb.com/title/tt0110912
7,tt0133093,The Matrix,The Matrix,1999,136.0,"Action,Sci-Fi",8.7,2243917,https://www.imdb.com/title/tt0133093
...,...,...,...,...,...,...,...,...,...
16247,tt3544218,Belgica,Belgica,2016,127.0,Drama,6.7,5001,https://www.imdb.com/title/tt3544218
16248,tt0101733,Dil Hai Ki Manta Nahin,Dil Hai Ki Manta Nahin,1991,154.0,"Adventure,Comedy,Drama",7.2,5001,https://www.imdb.com/title/tt0101733
16249,tt10994688,The Binge,The Binge,2020,98.0,Comedy,5.3,5000,https://www.imdb.com/title/tt10994688
16250,tt0263743,Billionaire,Milyarder,1987,96.0,"Comedy,Drama",7.5,5000,https://www.imdb.com/title/tt0263743
16251,tt1921078,Saint Petersburg,San Peterzburg,2010,120.0,"Comedy,Crime,Drama",6.4,5000,https://www.imdb.com/title/tt1921078

In [42]:
df.loc[(df['year'] < 2000) | (df['average_rating'] < 8.0), ['title', 'year', 'average_rating']]

                          title  year  average_rating
0      The Shawshank Redemption  1994             9.3
3                    Fight Club  1999             8.8
5                  Forrest Gump  1994             8.8
6                  Pulp Fiction  1994             8.8
7                    The Matrix  1999             8.7
...                         ...   ...             ...
16247                   Belgica  2016             6.7
16248    Dil Hai Ki Manta Nahin  1991             7.2
16249                 The Binge  2020             5.3
16250               Billionaire  1987             7.5
16251          Saint Petersburg  2010             6.4

[15708 rows x 3 columns]

In [ ]:
df